set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports rxf_n]
set_property IOSTANDARD LVCMOS33 [get_ports txe_n]
set_property IOSTANDARD LVCMOS33 [get_ports usb_clk]
set_property IOSTANDARD LVCMOS33 [get_ports wr_n]
set_property IOSTANDARD LVCMOS33 [get_ports {be[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {be[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {be[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {be[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wakeup[0]}]



set_property PACKAGE_PIN U17 [get_ports txe_n]
set_property PACKAGE_PIN P17 [get_ports {be[3]}]
set_property PACKAGE_PIN N17 [get_ports {be[2]}]
set_property PACKAGE_PIN P15 [get_ports {be[1]}]
set_property PACKAGE_PIN R16 [get_ports {be[0]}]
set_property PACKAGE_PIN R17 [get_ports {data[31]}]
set_property PACKAGE_PIN P16 [get_ports {data[30]}]
set_property PACKAGE_PIN P20 [get_ports {data[29]}]
set_property PACKAGE_PIN N15 [get_ports {data[28]}]
set_property PACKAGE_PIN N14 [get_ports {data[27]}]
set_property PACKAGE_PIN N13 [get_ports {data[26]}]
set_property PACKAGE_PIN P14 [get_ports {data[25]}]
set_property PACKAGE_PIN R14 [get_ports {data[24]}]
set_property PACKAGE_PIN R18 [get_ports {data[23]}]
set_property PACKAGE_PIN T18 [get_ports {data[22]}]
set_property PACKAGE_PIN U22 [get_ports {data[21]}]
set_property PACKAGE_PIN V22 [get_ports {data[20]}]
set_property PACKAGE_PIN Y18 [get_ports {data[19]}]
set_property PACKAGE_PIN Y19 [get_ports {data[18]}]
set_property PACKAGE_PIN W19 [get_ports {data[17]}]
set_property PACKAGE_PIN W20 [get_ports {data[16]}]
set_property PACKAGE_PIN Y21 [get_ports {data[15]}]
set_property PACKAGE_PIN U21 [get_ports {data[14]}]
set_property PACKAGE_PIN T21 [get_ports {data[13]}]
set_property PACKAGE_PIN W21 [get_ports {data[12]}]
set_property PACKAGE_PIN W22 [get_ports {data[11]}]
set_property PACKAGE_PIN T20 [get_ports {data[10]}]
set_property PACKAGE_PIN AB18 [get_ports {data[9]}]
set_property PACKAGE_PIN AA18 [get_ports {data[8]}]
set_property PACKAGE_PIN AA19 [get_ports {data[7]}]
set_property PACKAGE_PIN AB20 [get_ports {data[6]}]
set_property PACKAGE_PIN AA20 [get_ports {data[5]}]
set_property PACKAGE_PIN AA21 [get_ports {data[4]}]
set_property PACKAGE_PIN AB22 [get_ports {data[3]}]
set_property PACKAGE_PIN AB21 [get_ports {data[2]}]
set_property PACKAGE_PIN W17 [get_ports {data[1]}]
set_property PACKAGE_PIN V17 [get_ports {data[0]}]



set_property PACKAGE_PIN R19 [get_ports wr_n]
set_property PACKAGE_PIN Y22 [get_ports usb_clk]
set_property PACKAGE_PIN U18 [get_ports rxf_n]
set_property PACKAGE_PIN C13 [get_ports resetn]
set_property PACKAGE_PIN R4 [get_ports clk_in_clk_p]
set_property PACKAGE_PIN V20 [get_ports {wakeup[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets usb_clk_IBUF]

set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports clk_in_clk_p]

set_property SLEW SLOW [get_ports {wakeup[0]}]
set_property PULLTYPE PULLUP [get_ports {wakeup[0]}]

set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets Module_top_i/clk_wiz_0/inst/clk_in1_Module_top_clk_wiz_0_0]

# Generated clock cho sys_clk_i (100 MHz) của MIG
create_generated_clock -name clk_sys_100mhz -source [get_pins Module_top_clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1] -multiply_by 1 -divide_by 1 \   ;
[get_pins Module_top_i/mig_7series_0/sys_clk_i]

# Generated clock cho clk_ref_i (200 MHz) của MIG
create_generated_clock -name clk_ref_200mhz -source [get_pins Module_top_clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -multiply_by 1 -divide_by 1 [get_pins Module_top_i/mig_7series_0/clk_ref_i]

# Generated clock cho clk_ref_i (250 MHz) của MIG
create_generated_clock -name clk_ref_250mhz -source [get_pins Module_top_clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -multiply_by 1 -divide_by 1 [get_pins Module_top_i/mig_7series_0/clk_ref_i]

# Cut timing paths giữa ui_clk của MIG và 2 clock từ clk_wiz (chuẩn Xilinx)
set_false_path -from [get_clocks *ui_clk*] -to [get_clocks clk_out1_Module_top_clk_wiz_0_0]
set_false_path -from [get_clocks clk_out1_Module_top_clk_wiz_0_0] -to [get_clocks *ui_clk*]
set_false_path -from [get_clocks *ui_clk*] -to [get_clocks clk_out2_Module_top_clk_wiz_0_0]
set_false_path -from [get_clocks clk_out2_Module_top_clk_wiz_0_0] -to [get_clocks *ui_clk*]
set_false_path -from [get_clocks *ui_clk*] -to [get_clocks clk_out3_Module_top_clk_wiz_0_0]
set_false_path -from [get_clocks clk_out3_Module_top_clk_wiz_0_0] -to [get_clocks *ui_clk*]

set_clock_groups -asynchronous -group [get_clocks clk_out3_Module_top_clk_wiz_0_0] -group [get_clocks clk_pll_i]
set_clock_groups -asynchronous -group [get_clocks clk_out2_Module_top_clk_wiz_0_0] -group [get_clocks clk_pll_i]
set_clock_groups -asynchronous -group [get_clocks clk_out1_Module_top_clk_wiz_0_0] -group [get_clocks clk_pll_i]

set_property IOSTANDARD LVCMOS33 [get_ports xanh]
set_property IOSTANDARD LVCMOS33 [get_ports vang]
set_property PACKAGE_PIN L18 [get_ports vang]
set_property PACKAGE_PIN N19 [get_ports xanh]

set_property SLEW SLOW [get_ports {data[31]}]
set_property PULLTYPE PULLUP [get_ports {data[31]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property IOSTANDARD LVCMOS33 [get_ports CLR]
set_property IOSTANDARD LVCMOS33 [get_ports LDAC]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN G21 [get_ports miso]
set_property PACKAGE_PIN G22 [get_ports sclk]
set_property PACKAGE_PIN G20 [get_ports mosi]
set_property PACKAGE_PIN H20 [get_ports cs]
set_property PACKAGE_PIN H22 [get_ports LDAC]
set_property PACKAGE_PIN K21 [get_ports RST]
set_property PACKAGE_PIN J22 [get_ports CLR]
